name: "ruff-action"
description: "A GitHub Action to run Ruff, an extremely fast Python linter and code formatter."
author: "astral-sh"
inputs:
  args:
    description: "Arguments passed to Ruff. Use `ruff --help` to see available options. Defaults to `check`."
    required: false
    default: "check"
  src:
    description: "Source to run Ruff. Defaults to the current directory."
    required: false
    default: "."
  version:
    description: 'The version of Ruff to use, e.g., `0.6.0` Defaults to the latest version.'
    required: false
    default: ""
  changed-files:
    description: 'Whether to only run Ruff on changed files. Defaults to `false`.'
    required: false
    default: "false"
branding:
  color: "black"
  icon: "code"
runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      if: ${{ inputs.changed-files == 'true' }}
      uses: tj-actions/changed-files@v45
      with:
        files: '**.py'
    - run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          python $GITHUB_ACTION_PATH/action/main.py
        else
          python3 $GITHUB_ACTION_PATH/action/main.py
        fi
      env:
        RUFF_OUTPUT_FORMAT: github
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_SRC: ${{ inputs.src }}
        INPUT_VERSION: ${{ inputs.version }}
        IS_CHANGED_FILES_ENABLED: ${{ inputs.changed-files }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        pythonioencoding: utf-8
      shell: bash
