name: "ruff-action"
description: "A GitHub Action to run Ruff, an extremely fast Python linter and code formatter."
author: "astral-sh"
inputs:
  args:
    description: "Arguments passed to Ruff. Use `ruff --help` to see available options. Defaults to `check`."
    required: false
    default: "check"
  src:
    description: "Source to run Ruff. Defaults to the current directory."
    required: false
    default: ${{ github.workspace }}
  version:
    description: "The version of Ruff to use, e.g., `0.6.0` Defaults to the version in pyproject.toml or 'latest'."
    required: false
    default: ""
  version-file:
    description: "Path to a pyproject.toml or requirements.txt file to read the version from."
    required: false
  checksum:
    description: "The checksum of the ruff version to install"
    required: false
  github-token:
    description:
      "Used to increase the rate limit when retrieving versions and downloading
      ruff."
    required: false
    default: ${{ github.token }}
outputs:
  ruff-version:
    description: "The installed ruff version. Useful when using latest."
runs:
  using: "node20"
  main: "dist/ruff-action/index.js"
branding:
  icon: "code"
  color: "black"
