

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["B", "UP"]
fixable = ["I", "RUF100"]
unfixable = []

[tool.pyright]
typeCheckingMode = "lazy"
defineConstant = { DEBUG = true }

reportMissingImports = false
reportMissingTypeStubs = false
reportInvalidStringEscapeSequence = false

pythonVersion = "3.11"
pythonPlatform = "Linux"
